### ISSUE TITLE
Bêta test

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon-website#13]
Très beau site web.
Amélioration proposée : mettre en ligne une version bêta du simulateur 

Bon courage à toute l'équipe.

**Comment by lolocomotive** [comment]
J'ai mis un "coming soon" en attendant d'avoir fini d'implémenter le simu

**Comment by fmOOmf** [comment]
C'est fait. Bravo ! A clore.
Le Y 1.0 stable va sortir dans la foulée ?

**Comment by lolocomotive** [comment]
L'erreur 404 et l'accueuil -> accueil sont fix (normalement). J'aimerais encore ajouter un mode sombre pour le simulateur (je fermerai l'issue quand ca sera fait)

**Comment by fmOOmf** [comment]
Bonjour.
Super, je diffuse le lien.

**Comment by fmOOmf** [comment]
Lorsque le firmware passera en version stable, y aura-t-il (en plus du simulateur de la version stable), un simulateur de la version dev ou beta pour évaluation ?

**Comment by lolocomotive** [comment]
Pour l'instant le simulateur utilise la dernière beta mais c'est vrai que ça pourrait être intéressant d'avoir une manière de sélectionner un release Channel pour le simulateur. Il faudrait aussi une manière de sauvegarder les sessions et de les restaurer.

**Comment by fmOOmf** [comment]
Bonjour

Cadeau du jour : le simulateur en mode sombre est arrivé.
Petit retour : j'ai du mal à distinguer le bleu des caracteres des touches sur fond noir, ainsi que la position du "curseur" dans les menus, ou dans les applications "fonctions" ou "suite". 
=> Sur telephone je suis obligé de forcer la luminosité. Sur ordinateur, pas de soucis. 
Egalement une lisibilité un peu difficile pour moi quand je demande les infos sur un élément chimique dans "atomics". 

Peut être est il possible d'avoir un choix entre 2 thèmes (un sombre un clair), pour les cas où on utilise le simulateur sur son telephone ?

Sur ecran d'ordinateur, pas de soucis. Le rendu est vraiment réussi.

Bon courage à toute l'équipe.

**Comment by Yaya-Cout** [comment]
Cette issue peut-elle être fermée ?

---

Can this issue be closed ?

**Comment by fmOOmf** [comment]
Bonjour.
Pour moi oui. 
Merci à toute l'équipe. 

---

Yes. Thank you and the whole team.
