### ISSUE TITLE
[ Enhancement ] FAQ

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon-website#14]
Bonjour à toute l'équipe.

Suggestion : Créer un onglet FAQ, pour permettre à tous d'avoir la réponse à ses questions.

**Comment by lolocomotive** [comment]
Bonne idée, tu as des exemples de questions?

**Comment by fmOOmf** [comment]
Bonjour 

Quelques exemples de questions que je me suis posées.

- Quels sont les navigateurs requis pour une installation
- Comment sauvegarder tous les fichiers (python, de liseuse) de ma calculatrice avant mon changement de firmware
- Est-ce que mes fichiers pythons sont effacés quand j'installe une nouvelle version de firmware
- comment installer/effacer les applications externes
- Comment installer spécifiquement  (donc ajouter aux précédentes) une application externe
- Comment supprimer spécifiquement (donc n'effacer que celle-là) une application externe
- Comment ajouter des fichiers sur ma liseuse
- Comment créer un fichier liseuse à partir de ma calculatrice
- Pourquoi mes fichiers de liseuse sont-ils affichés deux fois
- Y a-t-il un moyen de tester mes fichiers liseuse sur le site web Upsilon avant de les copier sur ma calculatrice
- Comment copier des scripts pythons sur ma calculatrice
- Puis-je écrire mes scripts pythons sur mon ordinateur, les tester sur le simulateur, puis les copier sur ma calculatrice
- Puis-je modifier mon thème sans ré-installer le firmware
- Comment puis-je accéder à l'interface permettant la gestion des applications externes sans devoir installer le firmware
- Comment suggérer une amélioration du firmware
- Y a-t-il une liste des trucs et astuces,  combinaisons de touches, etc ... sur ma calculatrice
- Y a-t-il une liste des trucs et astuces,  combinaisons de touches, etc ... pour le simulateur

**Comment by fmOOmf** [comment]
Bonjour.

Suggestions complementaires:
- Puis-je installer Upsilon sur tous les modèles de Numworks (n0100, n0110)
- Que signifie "Numworks verrouillée" et comment puis je verifier si ma calculatrice est verrouillée ou non
-  Ma calculatrice tourne avec un firmware différent (Epsilon, Omega, Delta ...). Est-il possible d'installer Upsilon ? 
- Sera-il possible de revenir sur un autre firmware une fois Upsilon installé
- le mode examen de ma calculatrice est il conforme avec Upsilon
- Qu'est ce que la fonction recovery du site web ? Dans quel cas suis-je amené à l'utiliser  
- Je désire mettre à jour le firmware Upsilon. Devrais-je re-installer les applications externes ? Mes fichiers python et liseuses seront ils preservés ?
- Je suis intéressé par les applications externes proposées mais je n'ai pas bien compris ce qu'elles font. Où puis je en trouver une description ?
- Je souhaite écrire un fichier liseuse. Quelles contraintes dois-je respecter sur son nom et extension ? Quel est le format de fichier à respecter ? Un bon exemple de fichier est il installé avec la liseuse ?
- Je ne connais pas la syntaxe LaTex. Y a-t-il une liste des principales syntaxes utilisables avec la liseuse, et un lien vers un site me permettant d'approfondir les connaissances ?
- Je souhaite accéder à la bibliothèque de scripts proposée sur le site de Numworks. Ma calculatrice sera-t-elle mise à jour par Numworks (ce qui la verrouillerait). Y a-t-il une fonctionnalité  dans Upsilon me protégeant contre une installation accidentelle de firmware ?

**Comment by lolocomotive** [comment]
J'ai fait une FAQ où je réponds à la plpart de tes questions (pour l'instant que en anglais par contre)

**Comment by fmOOmf** [comment]
Bonjour.
Super ! Merci pour tous ce travail au service de cette nouvelle communauté Upsilon.

**Comment by fmOOmf** [comment]
Bonjour.
Quelques coquilles ont échappé à votre vigilance : "extenal"   "instal"  "instaler"  tranfert" .

**Comment by fmOOmf** [comment]
Bonsoir.
C'est vraiment un point mineur. 
Par contre un copier/coller malencontreux nous prive de la réponse à la question des "cheatsheet". Le suspense est insoutenable.
Bon courage à toute l'équipe.

**Comment by fmOOmf** [comment]
Bonoir à tous.

Une coquille a corriger sur le lien vers le guide de déverrouillage de omega.
Dans la FAQ :  https://guide.detomega.dev/
Au lieu de  : https://guide.getomega.dev/

**Comment by lolocomotive** [comment]
C'est corrigé.

**Comment by fmOOmf** [comment]
L'onglet FAQ est maintenant très complet.
=>  clôture du ticket .
