### ISSUE TITLE
[ Fonctionnalité liseuse en ligne ]

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon-website#15]
Bonjour à tous.

Une suggestion d'amélioration du site web : ajouter la possibilité pour le simulateur en ligne, de lire un fichier Liseuse de l'utilisateur, et d'afficher le résultat.
Cela permettrait de faciliter la création de fiches de lecture pour les utilisateurs : evaluation du résultat avant chargement sur la calculatrice.

Votre suggestion : installer un simulateur du firmware sur son PC est aussi une solution. 
Pour ceux comme moi qui ne savent pas comment installer le simulateur en local, quelques indications sont les bienvenues.

Merci à toute l'équipe Upsilon.

**Comment by lolocomotive** [comment]
Il faut effectivement que je fasse une page téléchargements avec des instructions pour le simulateur. Concernant l'affichage des fichiers de liseuse sur le simulateur en ligne je ne sais pas si c'est faisable et si oui il faut que je me renseigne comment. Si c'est pas trop compliqué j'implémenterai peut-être.

**Comment by Yaya-Cout** [comment]
Je sais qu'il y a une fuite de mémoire dans le simulateur natif au niveau des fichiers de la liseuse…

**Comment by fmOOmf** [comment]
Si c'est compliqué, un convertisseur txt vers pdf ou autre suffirait. Il faut bien sûr qu'il soit fidèle au rendu Latex de la liseuse).
L'essentiel est de pouvoir contrôler le rendu final pour faire toutes les corrections sur son PC (en ligne ou en local), avant implémentation dans la calculatrice.
