### ISSUE TITLE
[ Liseuse ] Complément de mode d'emploi

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon-website#16]
Bonsoir à toute l'équipe.

_Avant :_ 
Les fichiers *.txt contenant des balises LaTex étaient interprétés, et la liseuse affichait 2 fois le fichier : le premier présentait le texte brut, et le 2e fichier présentait le texte interprété.

_Maintenant (05/04/22)_ Le comportement a été amélioré : il me semble que : 
- Les fichiers *.txt sont affichés sans interprétation. L'extension *.txt devrait être utilisée pour du texte sans balise LaTex.
- Les fichiers *.urt sont interprétés. L'extension *.urt serait donc obligatoire pour du texte avec balise LaTex.

Suggestion : 
Si c'est mon interprétation est la bonne, pourriez-vous enrichir la description de la syntaxe de la Liseuse pour expliciter qu'un fichier avec balises Latex doit obligatoirement porter l'extension *.urt pour être interprété. 
Peut-être en profiter pour ajouter la description des commandes nouvellement ajoutées (#184).

Merci à vous !

**Comment by lolocomotive** [comment]
Je compte refaire la page de la liseuse avec des instructions correctes sur ce qu'on peut utiliser comme fichiers, comment les créer et comment les transférer parce que là c'est pas clair et il manque plein d'informations.

**Comment by fmOOmf** [comment]
Hello la fine équipe.

Le site web Upsilon est bien complet.
On peut fermer ce ticket si vous voulez.
