### ISSUE TITLE
[ FAQ/Accueil ] Coquilles + Mise à jour

### ISSUE THREAD

**Issue by fmOOmf** [UpsilonNumworks/Upsilon-website#27]
Bonjour à toute l'équipe

**PAGE FAQ :**  Quelques coquilles et mises à jour qui ont échappé à votre vigilance : 
- Lien vers le guide d'install omega erroné (**det**omega.dev => **get**omega.dev
![image](https://user-images.githubusercontent.com/98671961/169167334-307cdac8-457c-442d-bf9e-08fc8194f844.png)

- Le site du lien vers le tuto de la liseuse doit être mis à jour (..doc/**latex** => ..doc/**reader**
![image](https://user-images.githubusercontent.com/98671961/169164971-62f554be-5c21-434a-916a-b21a72d696f0.png)

- Pas de lien derrière le texte "Upsilon-website"
![image](https://user-images.githubusercontent.com/98671961/169165238-839e96d9-e12b-4a05-8635-77aa0aa2cbba.png)

- Mettre à jour le texte correspondant au retour vers Epsilon (il n'y a plus de menu USB).
![image](https://user-images.githubusercontent.com/98671961/169165540-4aedadae-1fd5-40e9-aacf-dc557f2a0ac9.png)

- Je changerais "**feuille de triche**" en "**liste d'astuces**" 
![image](https://user-images.githubusercontent.com/98671961/169165835-de44b583-694a-418f-82a3-f6bac78d3798.png)

**Page d'accueil** : une suggestion : 
On peut passer à côté d'informations très intéressantes de la page d'accueil si on ne pense pas à aller vers le bas de la page d'accueil, car rien n'indique qu'il y a de l'information plus bas.
=> Un bouton, un dessin, ou ce qu'il vous semblera clair, permettrait d'expliciter la présence d'info plus bas dans la page d'accueil.

Bon courage à toute l'équipe

---

Some wording typo to correct, links to update ...

**Comment by lolocomotive** [comment]
Merci beaucoup!
