### ISSUE TITLE
[ Enhancement ] Save locale

### ISSUE THREAD

**Issue by Yaya-Cout** [UpsilonNumworks/Upsilon-website#35]
Save active locale in localStorage

**Comment by lolocomotive** [comment]
I already started working on this but idk if I need to make a cookie prompt or something like that 🤷

**Comment by Yaya-Cout** [comment]
Take a look at 65b5cd8d45840bdbf294f50ebfd73e43d4a85a48, it uses the locale storage, so no cookies warning.

**Comment by lolocomotive** [comment]
I forgot I pushed that lmao
But then the locale should already be saved
