### ISSUE TITLE
add a link to the website in the "about" section

### ISSUE THREAD

**Issue by apoleon33** [UpsilonNumworks/Upsilon-website#36]
please

**Comment by Yaya-Cout** [comment]
Why do you want that ?

**Comment by apoleon33** [comment]
I never know where to find a link so i irremediably end up here everytime im searching for it.

**Comment by lemoustachu** [comment]
You could just go to https://github.com/UpsilonNumworks/Upsilon and click getupsilon.web.app in the description.
