### ISSUE TITLE
Make use of custom bin easier

### ISSUE THREAD

**Issue by BloomyInDev** [UpsilonNumworks/Upsilon-website#41]
Hey Upsilon Team,
I think the addition of custom binary on the website is good but, in my opinion, it can be better
When you add an dfu file to the website on custom binary it can be possible of select if you want internal, external or the two with an little explanation under it (like when you select your release channel)
It can make the use of an modded numworks easier
Thanks for reading this

**Comment by Yaya-Cout** [comment]
You can remove the internal or the external using the trash button.

**Comment by BloomyInDev** [comment]
Yea but it can make the epsilon install process easier for some person that don't know very much how it works
